name: Elevator
version: 1.0.0
main: com.MootComb.Elevator.Main
api-version: 1.13
author: MootComb
description: Elevator and Teleporter plugin

permissions:
  elevator.use:
    description: Allows using elevators
    default: true
  elevator.bypass:
    description: Bypass cooldown
    default: op
  elevator.teleport:
    description: Allows using teleporters
    default: true